# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.field.node.register.field_reference
  - field.field.node.register.field_register_type
  - field.field.node.register.field_value
  - node.type.register
id: node.register.default
targetEntityType: node
bundle: register
mode: default
content:
  field_reference:
    type: string
    weight: 0
    label: above
    settings: {}
    third_party_settings: {}
  field_register_type:
    type: list_default
    weight: 1
    label: above
    settings: {}
    third_party_settings: {}
  field_value:
    type: number_decimal
    weight: 2
    label: above
    settings: {}
    third_party_settings: {}
hidden: {}
