# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.field.taxonomy_term.category.field_image
  - taxonomy.vocabulary.category
id: taxonomy_term.category.default
targetEntityType: taxonomy_term
bundle: category
mode: default
content:
  field_image:
    type: entity_reference_autocomplete
    weight: 0
    region: content
    settings: {}
    third_party_settings: {}
hidden: {}
