# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.field.node.movement.field_final_quantity
  - field.field.node.movement.field_initial_quantity
  - field.field.node.movement.field_movement_type
  - field.field.node.movement.field_product
  - field.field.node.movement.field_product_code
  - field.field.node.movement.field_quantity
  - field.field.node.movement.field_reference
  - node.type.movement
id: node.movement.default
targetEntityType: node
bundle: movement
mode: default
content:
  field_product:
    type: string_textfield
    weight: 0
    region: content
    settings: {}
    third_party_settings: {}
  field_product_code:
    type: string_textfield
    weight: 1
    region: content
    settings: {}
    third_party_settings: {}
  field_initial_quantity:
    type: number
    weight: 2
    region: content
    settings: {}
    third_party_settings: {}
  field_quantity:
    type: number
    weight: 3
    region: content
    settings: {}
    third_party_settings: {}
  field_final_quantity:
    type: number
    weight: 4
    region: content
    settings: {}
    third_party_settings: {}
  field_movement_type:
    type: string_textfield
    weight: 5
    region: content
    settings: {}
    third_party_settings: {}
  field_reference:
    type: string_textfield
    weight: 6
    region: content
    settings: {}
    third_party_settings: {}
hidden: {}
