# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.field.node.locations.field_address
  - field.field.node.locations.field_customer_locations
  - field.field.node.locations.field_email_locations
  - field.field.node.locations.field_name
  - field.field.node.locations.field_person_name
  - field.field.node.locations.field_phone_locations
  - node.type.locations
id: node.locations.default
targetEntityType: node
bundle: locations
mode: default
content:
  field_name:
    type: string_textfield
    weight: 0
    region: content
    settings: {}
    third_party_settings: {}
  field_person_name:
    type: string_textfield
    weight: 1
    region: content
    settings: {}
    third_party_settings: {}
  field_email_locations:
    type: email_default
    weight: 2
    region: content
    settings: {}
    third_party_settings: {}
  field_phone_locations:
    type: string_textfield
    weight: 3
    region: content
    settings: {}
    third_party_settings: {}
  field_address:
    type: string_textfield
    weight: 4
    region: content
    settings: {}
    third_party_settings: {}
  field_customer_locations:
    type: entity_reference_autocomplete
    weight: 5
    region: content
    settings: {}
    third_party_settings: {}
hidden: {}
