# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.field.paragraph.payment.field_method
  - field.field.paragraph.payment.field_quantity
  - field.field.paragraph.payment.field_reference
  - paragraphs.paragraphs_type.payment
id: paragraph.payment.default
targetEntityType: paragraph
bundle: payment
mode: default
content:
  field_method:
    type: entity_reference_label
    weight: 0
    label: above
    settings: {}
    third_party_settings: {}
  field_reference:
    type: string
    weight: 1
    label: above
    settings: {}
    third_party_settings: {}
  field_quantity:
    type: number_decimal
    weight: 2
    label: above
    settings: {}
    third_party_settings: {}
hidden: {}
