# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_active
  - node.type.product
  module:
  - core
id: node.product.field_active
field_name: field_active
entity_type: node
bundle: product
label: Activo
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: boolean
