# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_document_item
  - node.type.document
  module:
  - core
  - entity_reference
id: node.document.field_document_item
field_name: field_document_item
entity_type: node
bundle: document
label: Item de documento
description: ''
required: true
translatable: true
default_value: []
default_value_callback: ''
settings:
  handler: default:paragraph
  handler_settings:
    target_bundles:
      document_item: document_item
    sort:
      field: _none
    auto_create: false
field_type: entity_reference
