# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.paragraph.field_reference
  - paragraphs.paragraphs_type.payment
  module:
  - core
id: paragraph.payment.field_reference
field_name: field_reference
entity_type: paragraph
bundle: payment
label: Referencia
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: string
