# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.paragraph.field_method
  - paragraphs.paragraphs_type.payment
  module:
  - core
  - taxonomy
id: paragraph.payment.field_method
field_name: field_method
entity_type: paragraph
bundle: payment
label: Metodo
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings:
  handler: default:taxonomy_term
  handler_settings:
    target_bundles:
      payment_method: payment_method
    sort:
      field: _none
    auto_create: false
field_type: entity_reference
