# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_email_customer
  - node.type.customer
  module:
  - core
id: node.customer.field_email_customer
field_name: field_email_customer
entity_type: node
bundle: customer
label: correo electrónico
description: ''
required: true
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: email
