# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_name
  - node.type.locations
  module:
  - core
id: node.locations.field_name
field_name: field_name
entity_type: node
bundle: locations
label: nombre
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: string
