# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_reference
  - node.type.debtors
  module:
  - core
id: node.debtors.field_reference
field_name: field_reference
entity_type: node
bundle: debtors
label: Referencia
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: string
