# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_document_nunber
  - node.type.supplier
  module:
  - core
id: node.supplier.field_document_nunber
field_name: field_document_nunber
entity_type: node
bundle: supplier
label: Númeor de documenot
description: ''
required: true
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: string
