# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_public_webpage
  - node.type.product
  module:
  - core
id: node.product.field_public_webpage
field_name: field_public_webpage
entity_type: node
bundle: product
label: Publico en sitio web
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: boolean
