# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_total
  - node.type.document
  module:
  - core
id: node.document.field_total
field_name: field_total
entity_type: node
bundle: document
label: Total
description: ''
required: true
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: float
