# Generado automáticamente a partir del inventario de entidades Saibher BMS
langcode: es
status: true
dependencies:
  config:
  - field.storage.node.field_description
  - node.type.product
  module:
  - text
id: node.product.field_description
field_name: field_description
entity_type: node
bundle: product
label: Descripción del producto
description: ''
required: false
translatable: true
default_value: []
default_value_callback: ''
settings: {}
field_type: text_long
