# Generado automáticamente a partir del inventario de entidades Saibher BMS
uuid: 524b69d1-7c9c-4e91-9593-1e49dfa9bde9
langcode: es
status: true
dependencies: {}
id: payment
label: Pago
icon_uuid: null
description: Pagos
behavior_plugins: {}
