_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: es
uuid: 9e48a3da-a7b9-4224-9796-ce82726efe4c
name: 'Saibher bms'
mail: developer@saibher.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
mail_notification: null
